llm:
  model: "gpt-5-nano"
  max_requests_per_minute: 250
  max_tokens_per_minute: 100000
  request_url: "https://api.openai.com/v1/chat/completions"
  token_encoding_name: "o200k_base"
  max_in_flight: 250

data:
  input_file: "data/pubmed_talazoparib.jsonl"
  output_file: "data/relations.jsonl"

logging:
  level: "INFO"
  log_file: "logs/pipeline.log"
  relation_log_file: "logs/relation_log.jsonl"
  logging_level: 20


relation_extraction:
  max_attempts: 5
  threshold: 0.55

named_entity_recognition:
  max_attempts: 5

umls:
  api_key: "8a8c8ead-cf26-40e9-986e-08b358bd9ad7"
  api_url: "https://uts-ws.nlm.nih.gov/rest"