llm:
  model: "gpt-5-nano-2025-08-07"
  max_requests_per_minute: 1500
  max_tokens_per_minute: 125000
  request_url: "https://api.openai.com/v1/chat/completions"
  token_encoding_name: "cl100k_base"

paths:
  input: "data/pubmed_talazoparib.jsonl"
  output: "data/relations.jsonl"
  log: "logs/relation_log.jsonl"

logging:
  level: "INFO"

relation_extraction:
  max_attempts: 5
  logging_level: 20
  threshold: 0.55

named_entity_recognition:
  max_attempts: 5
  logging_level: 20